### ISSUE TITLE
"create a virtualenv"?

### ISSUE THREAD

**Issue by ghost** [kumar303/unicode-in-python#5]
what does that mean, can you be more explicit please?

**EDIT**
okay I think I got it. However:

```
~/pytest/bin/python build.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
Wrote ./unicode.html
Couldn't get a file descriptor referring to the console
Traceback (most recent call last):
  File "build.py", line 30, in <module>
    main()
  File "build.py", line 27, in main
    check_call(['open', './index.html'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by kumar303** [comment]
Hi, sorry for the confusion. I added a link to how to set up a virtualenv: https://virtualenv.pypa.io/en/stable/

Fixed in https://github.com/kumar303/unicode-in-python/commit/82cf054be49049dec638df0faa6e9fa6cce17de3

As for your other error, it is one I've never seen before. It's saying it can't run the `open` command but that's ok, it was just there for convenience. Instead, you can open `index.html` in a browser to see the built slides.
